# Generated by Django 5.0.4 on 2024-04-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("First_Name", models.CharField(max_length=50)),
                ("Last_Name", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=50, unique=True)),
                ("Password", models.CharField(max_length=50)),
                ("Re_type_Your_Password", models.CharField(max_length=50)),
                ("Terms_Privacy_Policy", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
