# Generated by Django 5.0.4 on 2024-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0003_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Description", models.CharField(max_length=500)),
                ("Asset_Tag_Id", models.CharField(max_length=30)),
                ("Purchase_Date", models.DateField()),
                ("Brand", models.CharField(max_length=30)),
                ("Purchased_From", models.CharField(max_length=30)),
                ("Cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Model_Type", models.CharField(max_length=30)),
                (
                    "Serial_Number",
                    models.CharField(
                        default="",
                        max_length=20,
                        unique=True,
                        verbose_name="Serial Number",
                    ),
                ),
                ("Site", models.CharField(default="", max_length=300)),
                ("Category", models.CharField(default="", max_length=300)),
                ("Location", models.CharField(default="", max_length=300)),
                ("Department", models.CharField(default="", max_length=300)),
                (
                    "Assest_Photo",
                    models.ImageField(default="", upload_to="asset_photos/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="Email",
            field=models.EmailField(
                max_length=250, unique=True, verbose_name="Email Address"
            ),
        ),
    ]
