# Generated by Django 5.0.4 on 2024-04-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0004_assetdetails_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetdetails",
            name="Status",
            field=models.CharField(default="", max_length=30),
        ),
    ]
