# Generated by Django 5.0.4 on 2024-04-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0007_remove_assetdetails_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "Asset_Tag_ID",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("Asset_Name", models.CharField(max_length=100)),
                ("Description", models.TextField()),
                ("Purchase_From", models.CharField(max_length=100)),
                ("Purchase_Date", models.DateField()),
                ("Brand", models.CharField(max_length=50)),
                ("Model", models.CharField(max_length=50)),
                ("Serial_Number", models.CharField(max_length=50)),
                ("Cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Site", models.CharField(max_length=100)),
                ("Location", models.CharField(max_length=100)),
                ("Department", models.CharField(max_length=100)),
                ("Category", models.CharField(max_length=100)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Checked Out", "Checked Out"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_Name", models.CharField(max_length=100)),
                ("Employee_ID", models.CharField(max_length=50, unique=True)),
                ("Title", models.CharField(max_length=100)),
                ("Phone", models.CharField(max_length=15)),
                ("Email", models.EmailField(max_length=254)),
                ("Site", models.CharField(max_length=100)),
                ("Location", models.CharField(max_length=100)),
                ("Department", models.CharField(max_length=100)),
                ("Notes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Check_Out_Date", models.DateField(blank=True, null=True)),
                ("Check_In_Date", models.DateField(blank=True, null=True)),
                (
                    "Status",
                    models.CharField(
                        choices=[("Check Out", "Check Out"), ("Check In", "Check In")],
                        max_length=20,
                    ),
                ),
                ("Department", models.CharField(max_length=100)),
                ("Check_Out_To", models.CharField(max_length=100)),
                ("Due_Date", models.DateField(blank=True, null=True)),
                ("Check_Out_Notes", models.TextField(blank=True)),
                ("Check_In_Note", models.TextField(blank=True)),
                ("Email", models.EmailField(max_length=254)),
                (
                    "Asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="modules.asset"
                    ),
                ),
                (
                    "Assigned_To",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="modules.employee",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AssetDetails",
        ),
    ]
