# Generated by Django 5.0.4 on 2024-04-22 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0008_asset_employee_transaction_delete_assetdetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="Asset",
            new_name="Asset_Tag_ID",
        ),
    ]
