# Generated by Django 5.0.4 on 2024-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0010_alter_transaction_asset_tag_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="Asset_Photo",
            field=models.ImageField(blank=True, null=True, upload_to="asset_photos/"),
        ),
    ]
